/**
 * OMP extension: register the local Hermes proxy as an OMP LLM provider.
 *
 * Startup order:
 *   1. read config.json (policy)
 *   2. GET <baseUrl>/models from the proxy
 *   3. write the FULL catalog to models.discovered.json (atomic tmp+rename)
 *   4. register the filtered subset from that catalog
 *
 * Fallback chain when the proxy is unreachable: discovered cache -> seed
 * (models.json). Never registers an empty provider, never fails silently.
 *
 * Live model lists refresh through OMP's native `refreshModels` hook, so
 * `omp models refresh` and `/hermes-refresh` both work without a restart.
 */

import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import type {
	ExtensionAPI,
	ExtensionCommandContext,
	ProviderModelConfig,
} from "@earendil-works/pi-coding-agent";

// The allowlist, catalog discovery, and mapping live in a plain-JS module so the
// CLI audit scripts and this extension cannot drift apart.
import {
	fetchFreeModels as fetchProviderFreeModels,
	loadDotEnv,
	loadProviders as loadProviderDefs,
	mapModel as mapProviderModel,
	resolveKey as resolveProviderKey,
} from "./providers.mjs";

loadDotEnv();

const PROVIDER_ID = "verified-hermes";
const MODULE_DIR = dirname(fileURLToPath(import.meta.url));
/** Package root: the extension lives in <root>/src, data files sit beside package.json. */
const ROOT_DIR = join(MODULE_DIR, "..");

const CONFIG_PATH = join(ROOT_DIR, "config.json");
const CACHE_PATH = join(ROOT_DIR, "models.discovered.json");
const SEED_PATH = join(ROOT_DIR, "models.json");
// One file for every registered `verified-*` provider.
//
// This used to be "opencode.hermes.json" and carried only the Hermes block.
// That name was actively misleading: refreshing it looked like it was updating
// the multi-provider export, and a stale copy of it shadowed the real one.
const OPENCODE_PATH = join(ROOT_DIR, "opencode.providers.json");

const OPENCODE_COMMENT =
	"GENERATED by omp-hermes-proxy-extension from audit.json. Copy the provider blocks into " +
	"~/.config/opencode/opencode.jsonc. Only models that answered a real tool call during " +
	"the audit are listed. Regenerate with /hermes-refresh in OMP, or: node scripts/audit-models.mjs";

const THINKING_LEVELS = ["minimal", "low", "medium", "high", "xhigh", "max"] as const;

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

interface HermesConfig {
	baseUrl: string;
	apiKey: string;
	fetchTimeoutMs: number;
	probeTimeoutMs: number;
	freeOnly: boolean;
	requireChat: boolean;
	requireTools: boolean;
	requireReasoning: boolean;
	maxContextWindow: number;
	defaultMaxTokens: number;
	dedupeSnapshotVariants: boolean;
	verifyProbe: "free" | "all" | "off";
	probeConcurrency: number;
	probeMaxTokens: number;
	minModelsToAccept: number;
}

const DEFAULT_CONFIG: HermesConfig = {
	baseUrl: "http://localhost:8645/v1",
	apiKey: "HermesProxyLocal",
	fetchTimeoutMs: 5000,
	probeTimeoutMs: 30000,
	freeOnly: true,
	requireChat: true,
	requireTools: true,
	requireReasoning: false,
	maxContextWindow: 2_000_000,
	defaultMaxTokens: 8192,
	dedupeSnapshotVariants: true,
	verifyProbe: "free",
	probeConcurrency: 3,
	probeMaxTokens: 1,
	minModelsToAccept: 1,
};

function loadConfig(): HermesConfig {
	try {
		const parsed = JSON.parse(readFileSync(CONFIG_PATH, "utf-8")) as Partial<HermesConfig>;
		return { ...DEFAULT_CONFIG, ...parsed };
	} catch {
		return { ...DEFAULT_CONFIG };
	}
}

// ---------------------------------------------------------------------------
// Wire types (the proxy speaks OpenRouter's /v1/models schema)
// ---------------------------------------------------------------------------

interface WireModel {
	id?: string;
	name?: string;
	context_length?: number;
	pricing?: { prompt?: string; completion?: string };
	architecture?: { input_modalities?: string[]; output_modalities?: string[] };
	reasoning?: {
		mandatory?: boolean;
		default_enabled?: boolean;
		supported_efforts?: string[];
		default_effort?: string;
	};
	top_provider?: { max_completion_tokens?: number };
	supported_parameters?: string[];
	expiration_date?: string | null;
}

function toPrice(value: string | undefined): number {
	const parsed = Number(value);
	return Number.isFinite(parsed) && parsed > 0 ? parsed : 0;
}

/**
 * A model is free when BOTH sides of its price are zero, or when the id carries
 * the ":free" marker.
 *
 * Both conditions are required. The catalog contains 34 asymmetric entries
 * (embeddings, rerankers) priced 0 on completion but non-zero on prompt, so an
 * OR on a single price field would advertise those as free. Price alone is also
 * not sufficient: zero-cost models exist whose id has no ":free" marker, so a
 * name-only filter drops them.
 */
function isFree(model: WireModel): boolean {
	if ((model.id ?? "").includes(":free")) return true;
	return toPrice(model.pricing?.prompt) === 0 && toPrice(model.pricing?.completion) === 0;
}

function isChatCapable(model: WireModel): boolean {
	const input = model.architecture?.input_modalities;
	const output = model.architecture?.output_modalities;
	if (!input || !output) return false;
	return input.includes("text") && output.includes("text");
}

function supportsTools(model: WireModel): boolean {
	return (model.supported_parameters ?? []).includes("tools");
}

/** Strip a trailing dated snapshot suffix: "foo-20260926" -> "foo". */
function snapshotBase(id: string): string {
	return id.replace(/-(\d{8})$/, "").replace(/:batch$/, "");
}

// ---------------------------------------------------------------------------
// Mapping
// ---------------------------------------------------------------------------

function buildThinkingLevelMap(model: WireModel): Record<string, string | null> | undefined {
	const reasoning = model.reasoning;
	if (!reasoning) return undefined;
	const efforts = reasoning.supported_efforts;
	// No advertised vocabulary: leave the map off so OMP keeps its defaults.
	if (!efforts || efforts.length === 0) return undefined;

	const map: Record<string, string | null> = {};
	for (const level of THINKING_LEVELS) {
		map[level] = efforts.includes(level) ? level : null;
	}
	if (reasoning.mandatory) {
		// Reasoning cannot be switched off on this model.
		map.off = null;
	} else if (efforts.includes("none")) {
		map.off = "none";
	}
	return map;
}

function mapModel(model: WireModel, config: HermesConfig): ProviderModelConfig | null {
	if (!model.id) return null;

	const modalities = model.architecture?.input_modalities ?? [];
	const input: ("text" | "image")[] = [];
	if (modalities.includes("text")) input.push("text");
	if (modalities.includes("image")) input.push("image");
	if (input.length === 0) input.push("text");

	const contextWindow = Math.min(model.context_length ?? 0, config.maxContextWindow);
	if (contextWindow <= 0) return null;

	const advertisedMax = model.top_provider?.max_completion_tokens;
	const maxTokens =
		typeof advertisedMax === "number" && advertisedMax > 0
			? Math.min(advertisedMax, contextWindow)
			: Math.min(config.defaultMaxTokens, contextWindow);

	const entry: ProviderModelConfig = {
		id: model.id,
		name: model.name ?? model.id,
		reasoning: model.reasoning !== undefined,
		input,
		// The proxy quotes per-token prices; OMP expects per-million-token rates.
		cost: {
			input: toPrice(model.pricing?.prompt) * 1e6,
			output: toPrice(model.pricing?.completion) * 1e6,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow,
		maxTokens,
	};

	const thinkingLevelMap = buildThinkingLevelMap(model);
	if (thinkingLevelMap) entry.thinkingLevelMap = thinkingLevelMap;

	return entry;
}

interface Selection {
	wire: WireModel[];
	models: ProviderModelConfig[];
	rejected: { id: string; reason: string }[];
}

/** Wire records by model id, for consumers that need the raw catalog fields. */
let WIRE_BY_ID = new Map<string, WireModel>();

function selectModels(all: WireModel[], config: HermesConfig): Selection {
	const rejected: { id: string; reason: string }[] = [];
	const seen = new Set<string>();
	const wire: WireModel[] = [];

	for (const model of all) {
		if (!model.id) continue;

		if (config.freeOnly && !isFree(model)) {
			rejected.push({ id: model.id, reason: "paid" });
			continue;
		}
		if (config.requireChat && !isChatCapable(model)) {
			rejected.push({ id: model.id, reason: "not-chat" });
			continue;
		}
		if (config.requireTools && !supportsTools(model)) {
			rejected.push({ id: model.id, reason: "no-tools" });
			continue;
		}
		if (config.requireReasoning && model.reasoning === undefined) {
			rejected.push({ id: model.id, reason: "no-reasoning" });
			continue;
		}
		if (config.dedupeSnapshotVariants) {
			const base = snapshotBase(model.id);
			if (seen.has(base)) {
				rejected.push({ id: model.id, reason: "duplicate-variant" });
				continue;
			}
			seen.add(base);
		}
		wire.push(model);
	}

	const models = wire
		.map((model) => mapModel(model, config))
		.filter((model): model is ProviderModelConfig => model !== null);

	WIRE_BY_ID = new Map(wire.filter((m) => m.id).map((m) => [m.id as string, m]));

	return { wire, models, rejected };
}

// ---------------------------------------------------------------------------
// Cache file
// ---------------------------------------------------------------------------

interface ProbeResult {
	status: number | string;
	ok: boolean;
	checkedAt: string;
	detail?: string;
}

interface CacheFile {
	version: number;
	generatedAt: string;
	source: "proxy" | "cache" | "seed";
	baseUrl: string;
	catalogTotal: number;
	selectedTotal: number;
	catalog: WireModel[];
	probes?: Record<string, ProbeResult>;
}

function writeCache(cache: CacheFile): void {
	try {
		mkdirSync(dirname(CACHE_PATH), { recursive: true });
		// Write to a sibling temp file, then rename. rename() is atomic on the same
		// filesystem, so an interrupted write can never truncate the live cache.
		const tmp = `${CACHE_PATH}.${process.pid}.tmp`;
		writeFileSync(tmp, `${JSON.stringify(cache, null, 2)}\n`, "utf-8");
		renameSync(tmp, CACHE_PATH);
	} catch (error) {
		report(`could not write cache: ${errorMessage(error)}`);
	}
}

function readCache(): CacheFile | null {
	try {
		if (!existsSync(CACHE_PATH)) return null;
		const parsed = JSON.parse(readFileSync(CACHE_PATH, "utf-8")) as CacheFile;
		if (parsed.version !== 1 || !Array.isArray(parsed.catalog)) return null;
		return parsed;
	} catch {
		return null;
	}
}

function readSeed(): WireModel[] {
	try {
		const parsed = JSON.parse(readFileSync(SEED_PATH, "utf-8")) as
			| { catalog?: WireModel[] }
			| WireModel[];
		if (Array.isArray(parsed)) return parsed;
		if (Array.isArray(parsed.catalog)) return parsed.catalog;
		return [];
	} catch {
		return [];
	}
}

// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------
// opencode export
// ---------------------------------------------------------------------------

/**
 * The opencode export is owned by the audit, not by this extension.
 *
 * Both used to write opencode.providers.json from different sources: this one
 * from whatever had happened to register in OMP, the audit from its own probe
 * results. When both ran they disagreed, and it was never clear which was
 * authoritative.
 *
 * The audit has the stronger claim. It sees the stability history, and a model
 * only belongs in a file whose name promises verification if it has passed more
 * than once. Registration order and probe history are different inputs, and only
 * one of them survives a restart.
 */

// Network
// ---------------------------------------------------------------------------

function errorMessage(error: unknown): string {
	return error instanceof Error ? error.message : String(error);
}

let logSink: ((message: string) => void) | undefined;
function report(message: string): void {
	if (logSink) logSink(message);
}

async function fetchCatalog(baseUrl: string, apiKey: string, timeoutMs: number): Promise<WireModel[]> {
	const controller = new AbortController();
	const timer = setTimeout(() => controller.abort(), timeoutMs);
	try {
		const response = await fetch(`${baseUrl}/models`, {
			headers: { Authorization: `Bearer ${apiKey}` },
			signal: controller.signal,
		});
		if (!response.ok) throw new Error(`HTTP ${response.status}`);
		const body = (await response.json()) as { data?: WireModel[] };
		if (!Array.isArray(body.data)) throw new Error("malformed catalog: no data array");
		return body.data;
	} finally {
		clearTimeout(timer);
	}
}

/**
 * One-token completion confirming a listed model is actually reachable.
 * Catalog presence is not availability: a free model can stay listed while the
 * proxy answers 404 (retired) or 429 (upstream at capacity).
 */
async function probeModel(
	model: WireModel,
	baseUrl: string,
	apiKey: string,
	config: HermesConfig,
): Promise<ProbeResult> {
	const checkedAt = new Date().toISOString();
	const controller = new AbortController();
	const timer = setTimeout(() => controller.abort(), config.probeTimeoutMs);
	try {
		const response = await fetch(`${baseUrl}/chat/completions`, {
			method: "POST",
			headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
			body: JSON.stringify({
				model: model.id,
				messages: [{ role: "user", content: "hi" }],
				max_tokens: config.probeMaxTokens,
				stream: false,
			}),
			signal: controller.signal,
		});
		if (response.ok) return { status: response.status, ok: true, checkedAt };
		const detail = (await response.text()).slice(0, 200);
		return { status: response.status, ok: false, checkedAt, detail };
	} catch (error) {
		return { status: "error", ok: false, checkedAt, detail: errorMessage(error).slice(0, 200) };
	} finally {
		clearTimeout(timer);
	}
}

async function runProbes(
	models: WireModel[],
	baseUrl: string,
	apiKey: string,
	config: HermesConfig,
): Promise<Record<string, ProbeResult>> {
	const results: Record<string, ProbeResult> = {};
	const limit = Math.max(1, config.probeConcurrency);
	let cursor = 0;

	async function worker(): Promise<void> {
		while (cursor < models.length) {
			const model = models[cursor++];
			if (!model?.id) continue;
			results[model.id] = await probeModel(model, baseUrl, apiKey, config);
		}
	}

	await Promise.all(Array.from({ length: Math.min(limit, models.length) }, worker));
	return results;
}

// ---------------------------------------------------------------------------
// Load pipeline
// ---------------------------------------------------------------------------

interface LoadResult {
	models: ProviderModelConfig[];
	source: CacheFile["source"];
	catalogTotal: number;
	generatedAt?: string;
	probes?: Record<string, ProbeResult>;
	note?: string;
}

async function loadCatalog(config: HermesConfig, allowNetwork: boolean): Promise<LoadResult> {
	let source: CacheFile["source"] = "seed";
	let catalogTotal = 0;
	let note: string | undefined;

	if (allowNetwork) {
		try {
			const catalog = await fetchCatalog(config.baseUrl, config.apiKey, config.fetchTimeoutMs);
			catalogTotal = catalog.length;
			const selection = selectModels(catalog, config);
			if (selection.models.length >= config.minModelsToAccept) {
				const generatedAt = new Date().toISOString();
				let probes: Record<string, ProbeResult> | undefined;
				if (config.verifyProbe !== "off") {
					const targets =
						config.verifyProbe === "all" ? selection.wire : selection.wire.filter(isFree);
					probes = await runProbes(targets, config.baseUrl, config.apiKey, config);
				}
				writeCache({
					version: 1,
					generatedAt,
					source: "proxy",
					baseUrl: config.baseUrl,
					catalogTotal,
					selectedTotal: selection.wire.length,
					catalog: selection.wire,
					probes,
				});
				return {
					models: selection.models,
					source: "proxy",
					catalogTotal,
					generatedAt,
					probes,
					note,
				};
			}
			note = `proxy returned ${selection.models.length} usable models, below minimum ${config.minModelsToAccept}`;
		} catch (error) {
			note = `proxy unreachable: ${errorMessage(error)}`;
		}
	}

	const cache = readCache();
	if (cache && cache.catalog.length > 0) {
		const selection = selectModels(cache.catalog, config);
		if (selection.models.length >= config.minModelsToAccept) {
			report(`verified-hermes: using cache from ${cache.generatedAt} (${note ?? "no network"})`);
			return {
				models: selection.models,
				source: "cache",
				catalogTotal: cache.catalogTotal,
				generatedAt: cache.generatedAt,
				probes: cache.probes,
				note,
			};
		}
		note = `${note ?? "cache unusable"}; cache had ${selection.models.length} usable models`;
	}

	const seed = readSeed();
	const seedSelection = selectModels(seed, config);
	if (seedSelection.models.length === 0) {
		report(`verified-hermes: no models available (${note ?? "all sources empty"})`);
		return { models: [], source: "seed", catalogTotal: 0, note };
	}
	report(`verified-hermes: falling back to seed models.json (${note ?? "no network, no cache"})`);
	return { models: seedSelection.models, source: "seed", catalogTotal: seed.length, note };
}

// ---------------------------------------------------------------------------
// Extension entry
// ---------------------------------------------------------------------------

function providerConfig(config: HermesConfig, models: ProviderModelConfig[]) {
	return {
		name: "Hermes Proxy",
		baseUrl: config.baseUrl,
		apiKey: config.apiKey,
		authHeader: true,
		api: "openai-completions",
		models,
	};
}

export default async function (pi: ExtensionAPI): Promise<void> {
	const config = loadConfig();
	let last: LoadResult = { models: [], source: "seed", catalogTotal: 0 };

	async function refresh(): Promise<ProviderModelConfig[]> {
		const result = await loadCatalog(config, true);
		last = result;
		if (result.models.length === 0) {
			report("verified-hermes: refresh produced no models, keeping previous list");
		}
		return result.models;
	}

	// Populate eagerly so startup model selection and `omp --list-models` see the
	// provider. Pi awaits async extension factories before continuing.
	let initial: ProviderModelConfig[] = [];
	try {
		initial = await refresh();
	} catch (error) {
		report(`verified-hermes: initial load failed: ${errorMessage(error)}`);
	}

	pi.registerProvider(PROVIDER_ID, {
		...providerConfig(config, initial),
		async refreshModels(context) {
			// Offline init phase, or a cancelled refresh: keep the current list.
			if (!context.allowNetwork || context.signal.aborted) return last.models;
			return refresh();
		},
	});

	pi.registerCommand("hermes-refresh", {
		description: "Re-fetch the Hermes proxy catalog and re-register verified-hermes models",
		handler: async (_args: string, ctx: ExtensionCommandContext) => {
			ctx.ui.notify("verified-hermes: refreshing catalog...");
			const models = await refresh();
			// After initial load these take effect immediately, no /reload needed.
			pi.unregisterProvider(PROVIDER_ID);
			pi.registerProvider(PROVIDER_ID, providerConfig(config, models));
			ctx.ui.notify(describe(last), models.length > 0 ? "info" : "error");
		},
	});

	pi.registerCommand("hermes-status", {
		description: "Show Hermes proxy model source, counts, and last probe results",
		handler: async (_args: string, ctx: ExtensionCommandContext) => {
			ctx.ui.notify(describe(last), "info");
		},
	});

	pi.on("session_start", async () => {
		// Refresh once the session is live so startup is not blocked by the probe pass.
		void refresh();
	});

	registerAdditionalProviders(pi);
}

/**
 * Register every enabled provider in the allowlist that the Hermes path does
 * not already cover, as a `verified-<id>` provider.
 *
 * Two deliberate properties:
 *
 * 1. Only models the audit cleared are registered. OMP's picker otherwise shows
 *    every model an upstream advertises, including ones that answer 402, 429,
 *    or return nothing, so choosing a provider there means triaging 18
 *    candidates to find the 13 that work. A `verified-*` list is short and every
 *    entry works.
 *
 * 2. Providers stay separate rather than merged. Model ids collide across
 *    upstreams — `stealth/space-bunny-alpha` is served by Hermes, Cline and
 *    Kilo — and one merged provider cannot route three baseUrls with three
 *    different credentials anyway.
 */
function registerAdditionalProviders(pi: ExtensionAPI): void {
	const extra = loadProviderDefs().filter(
		(def) => def.enabled !== false && def.id !== "hermes" && def.baseUrl,
	);
	if (extra.length === 0) return;

	const verified = loadVerifiedIds();

	for (const def of extra) {
		const key = resolveProviderKey(def);
		const providerId = `verified-${def.id}`;

		const load = async (): Promise<ProviderModelConfig[]> => {
			const catalog = await fetchProviderFreeModels(def as never);
			const mapped = catalog.models
				// A verdict exists and is the authority: register only what is
				// stable. A null verdict means the audit has never run, so fall
				// back to the full free list rather than an empty picker.
				//
				// Note `verified === null` and `verified.size === 0` are NOT the
				// same: the first is "no audit yet", the second is "the audit ran
				// and nothing qualified". Treating the second as the first
				// registers the whole catalogue, defeating the rule.
				.filter((m) => verified === null || verified.has(`${def.id}/${String((m as { id?: string }).id)}`))
				.map((model) => mapProviderModel(model as never, { maxContextWindow: 2_000_000 }))
				.filter(Boolean) as unknown as ProviderModelConfig[];
			return mapped;
		};

		void (async () => {
			let models: ProviderModelConfig[] = [];
			try {
				models = await load();
			} catch (error) {
				report(`${providerId}: initial load failed: ${errorMessage(error)}`);
			}
			if (models.length === 0) {
				report(`${providerId}: no verified models — run: node scripts/audit-models.mjs --provider ${def.id}`);
				return;
			}

			pi.registerProvider(providerId, {
				name: `${def.label} (verified)`,
				baseUrl: def.baseUrl,
				// OMP requires a non-empty apiKey for any provider that defines
				// models. Cline and Kilo both authenticate, so this is the real
				// token rather than a placeholder.
				apiKey: key,
				authHeader: true,
				api: "openai-completions",
				// The provider's own SDK-identity headers must ride along, or
				// gated models answer 403 and look dead.
				headers: { ...(def.headers ?? {}) },
				models,
				async refreshModels(context: { allowNetwork?: boolean; signal?: AbortSignal }) {
					if (!context?.allowNetwork || context?.signal?.aborted) return models;
					try {
						models = await load();
					} catch (error) {
						report(`${providerId}: refresh failed: ${errorMessage(error)}`);
					}
					return models;
				},
			} as never);

			report(`${providerId}: registered ${models.length} verified model(s) from ${def.label}`);

		})();
	}
}

/**
 * Read the audit's passing model ids, keyed as `<providerId>/<modelId>`.
 *
 * Returns an empty set when no audit exists yet, which callers treat as
 * "no filtering available" rather than "nothing passed" — the two very
 * different cases must not collapse.
 */
interface StableDoc {
	generatedAt?: string;
	rule?: string;
	providers?: { id: string; models?: { id: string; status: string; reason?: string }[] }[];
}

function readStable(): StableDoc | null {
	const path = join(MODULE_DIR, "..", "audit-stable.json");
	if (!existsSync(path)) return null;
	try {
		return JSON.parse(readFileSync(path, "utf-8")) as StableDoc;
	} catch {
		return null;
	}
}

/**
 * Model ids eligible for a `verified-*` provider, keyed `<providerId>/<modelId>`.
 *
 * This reads the stability verdict rather than the last audit. A single pass
 * cannot tell a working model from a lucky one: our own eval scored one model
 * 100, 33 and 0 on three identical runs, and providers are no steadier. A model
 * earns the `verified-` name by passing at least twice in the recent window.
 *
 * Returns null when there is no verdict yet, which callers treat as "no
 * filtering available". An empty set means the verdict exists and nothing
 * qualified. Collapsing those two is dangerous: right after a first run every
 * model is "new", and reading that as "no filter" would register the entire
 * free catalogue — the exact opposite of the rule.
 */
/**
 * Statuses that earn a place in the picker.
 *
 * Must stay in step with PICKER_STATUSES in scripts/audit-history.mjs. Kept
 * as a literal rather than an import because the extension runs inside OMP's
 * runtime and must not depend on a build step to stay correct.
 */
const PICKER_STATUSES = new Set(["stable", "known-good", "unstable"]);

function loadVerifiedIds(): Set<string> | null {
	const stable = readStable();
	if (!stable) return null;
	try {
		const ids = new Set<string>();
		for (const provider of stable.providers ?? []) {
			for (const model of provider.models ?? []) {
				// `stable` is the proven tier: passed 2 of the last 3 runs.
				//
				// `known-good` and `unstable` are provisional — the model has
				// worked at least once and nothing permanent has happened to it.
				// They are included deliberately: a throttle or timeout says
				// the provider was busy, not that the model is bad, and
				// dropping it would churn the owner's configuration on a busy
				// afternoon for no gain.
				//
				// `rejected` (never worked), `retired` (permanently gone) and
				// `unknown` (never actually reached) earn no slot.
				if (PICKER_STATUSES.has(model.status)) ids.add(`${provider.id}/${model.id}`);
			}
		}
		return ids;
	} catch {
		return new Set();
	}
}

function describe(result: LoadResult): string {
	const lines = [
		`verified-hermes: ${result.models.length} model(s) from ${result.source}` +
			(result.catalogTotal ? ` (catalog ${result.catalogTotal})` : ""),
	];
	if (result.generatedAt) lines.push(`  catalog written: ${result.generatedAt}`);
	if (result.note) lines.push(`  note: ${result.note}`);
	if (result.probes) {
		const entries = Object.entries(result.probes);
		const ok = entries.filter(([, probe]) => probe.ok).length;
		lines.push(`  probes: ${ok}/${entries.length} reachable`);
		for (const [id, probe] of entries) {
			if (probe.ok) continue;
			lines.push(`    ${id}: ${probe.status}${probe.detail ? ` ${probe.detail}` : ""}`);
		}
	}
	return lines.join("\n");
}
